rm_driver:
  ros__parameters:
    #robot param
    arm_ip: "192.168.1.18"        #设置TCP连接时的IP
    tcp_port: 8080                #设置TCP连接时的端口

    arm_type: "RM_63"             #机械臂型号设置
    arm_dof: 6                    #机械臂自由度设置

    udp_ip: "192.168.1.10"        #设置udp主动上报IP
    udp_cycle: 5                  #udp主动上报周期，需要是5的倍数。
    udp_port: 8089                #设置udp主动上报端口
    udp_force_coordinate: 0       #设置系统受力时六维力的基准坐标，0为传感器坐标系 1为当前工作坐标系 2为当前工具坐标系
    udp_hand: false               #设置灵巧手udp主动上报使能

    trajectory_mode: 0            #设置高跟随模式下，支持多种模式，0-完全透传模式、1-曲线拟合模式、2-滤波模式
    radio: 0                      #设置曲线拟合模式下平滑系数（范围0-100）或者滤波模式下的滤波参数（范围0-1000），数值越大表示平滑效果越好