controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

rm_group_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
